What I did:
DavidZagury/sonic-swss pull request #1
Opened 2021-01-13 12:35 UTC by DavidZagury

Added class in orchagent named MonitorTxError - This class will monitor ports TX error counters, and will change the port status if the TX error is above a threshold
 Added it to the orchs list in orchdaemon class

Why I did it

How I verified it

Details if related

**What I did**

**Why I did it**

**How I verified it**

**Details if related**

2021-01-13 16:14 UTC, DavidZagury commented on orchagent/MonitorTxError.cpp
> +	SWSS_LOG_NOTICE("DEDDY MonitorTxError doTask consumer tableName %s\n", tableName.c_str());
Remove DEDDY from logs

2021-01-13 16:15 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +	SWSS_LOG_NOTICE("DEDDY MonitorTxError doTask consumer tableName %s\n", tableName.c_str());
Move to debug

2021-01-14 07:45 UTC, liorghub requested changes

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +}
Add new line at eof

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +			return;
Change return to continue

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +
Remove enter

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +void MonitorTxError::updatePortState(string oidStr, Port port)
Use reference for port

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +	txErrValue = stoul(txErrStrValue);
Use try catch sice stoul is not safe

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +
Remove redundant enters

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +	SWSS_LOG_NOTICE("DEDDY MonitorTxError initialized\n");
move to debug

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +
Remove enter

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.cpp
> +
Remove enter

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +}
why do we need this include?

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +
Remove enters

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +
Remove enters

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +	map <string, string> m_portsStringsMap;
m_portsStringsMap, do we need it?

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +	// map<string, uint64_t> m_currTxCounters;
Remove comment

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +	uint64_t m_threshold = TX_ERROR_DEFAULT_THRESHOLD;
Add _sec to variable name

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +	int m_poolingPeriod = TX_ERROR_CHECK_DEFAULT_TIMER;
Add _packets to var name

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +//    static void updateConfig(SyncMap op);
Remove all enters and updateConfig

2021-01-14 07:45 UTC, liorghub commented on orchagent/MonitorTxError.h
> +#endif //SONIC_SWSS_MONITORTXERROR_H
Remove all enters and add one enter at eof.

2021-01-14 07:45 UTC, liorghub commented on orchagent/orchdaemon.cpp
> +#include "MonitorTxError.h"
Move to orchdaemon.h

2021-03-08 10:38 UTC, closed without merging