[teammgrd]:Create unique LACP key for port-channel
DavidZagury/sonic-swss pull request #2
Opened 2021-01-25 17:34 UTC by DavidZagury

**What I did**
When a member port is added to port-channel, create a unique lacp-key by incrementing the last key created.

**Why I did it**
If LACP key is not set, then the peer will not be able to distinguish the ports which are connected to different port-channels, as it will receive the lacp key as 0 for all the ports from different port-channels.

**How I verified it**

**Details if related**

2021-01-26 13:20 UTC, liat-grozovik reviewed
please add comments to the code and the logic behind it
what is the logic of the key and why unique is required?

need to verify it it works in fastboot and warm boot as well

also, as this is behaviour change i believe we should raise it first with MSFT. Please take it with Volodymyr.

2021-01-26 13:33 UTC, liat-grozovik commented
Also, there are community LAG tests. need to check if this PR does not break the test and if so need to verify it.

2021-02-09 12:00 UTC, stepanblyschak requested changes

2021-02-09 12:00 UTC, stepanblyschak commented on cfgmgr/teammgr.cpp
> +    }
Could you please move this to a seperate function ```generateUniqueId(name)``` and cover it with unit test and cover it with interesting scenarios (PortChannel0, PortChannel01, PortChannel65536, PortChannel9999, PortChannelInvalid)?

2021-02-09 12:00 UTC, stepanblyschak commented on cfgmgr/teammgr.cpp
> +        keyId = (uint16_t)std::stoul("1" + lag.substr(lag.find_first_of("0123456789")));
```suggestion
        keyId = static_cast<unit16_t>(std::stoul("1" + lag.substr(lag.find_first_of("0123456789"))));
```

2021-02-09 12:00 UTC, stepanblyschak commented on cfgmgr/teammgr.cpp
> +        << " '{\"lacp_key\":"
I think that even with deterministic key you will create a disruption when upgrading from SONiC that does not support this feature to SONiC version with this feature. In old life the key was 0 (default) in new life it is generated based on port channel name.
This can be solved if it is a part of teamd warm start logic.
If you detect warmboot do not reconfigure "lacp_key", lacp key has to restore from the saved LACP PDU in teamd, teamd already saves lacp key from old life in the PDU.
Wonder if we can add lacp_key in warm restore logic in teamd https://github.com/Azure/sonic-buildimage/blob/master/src/libteam/patch/0008-libteam-Add-warm_reboot-mode.patch#L242?

2021-03-02 12:54 UTC, stepanblyschak approved these changes

2021-03-04 20:44 UTC, liat-grozovik commented
@DavidZagury where do we stands with this PR?
- issue is fixed?
- issue has been validated? as well as warmboot?
- sonic-mgmt tests were running with no issues related to the code changes?
- internal checkers are passing?

2021-03-08 08:15 UTC, closed without merging